apiVersion: apps/v1
kind: Deployment
metadata:
  name: roman-numeral-api
  labels:
    app: roman-numeral-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roman-numeral-api
  template:
    metadata:
      labels:
        app: roman-numeral-api
    spec:
      containers:
      - name: roman-numeral-api
        image: docker.io/raymondwcs/to_roman_numeral:backend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: roman-numeral-api
spec:
  type: NodePort
  selector:
    app: roman-numeral-api
  ports:
    - protocol: TCP
      nodePort: 32000
      port: 3000
      targetPort: 3000 