apiVersion: v1
kind: Service
metadata:
  name: roman-numeral
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      nodePort: 32000
      port: 3000
      targetPort: 3000 
