apiVersion: apps/v1
kind: Deployment
metadata:
  name: roman-numeral-frontend
  labels:
    app: roman-numeral-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roman-numeral-frontend
  template:
    metadata:
      labels:
        app: roman-numeral-frontend
    spec:
      containers:
      - name: roman-numeral-frontend
        image: docker.io/raymondwcs/to_roman_numeral:frontend
        imagePullPolicy: Always
        env:
        - name: ROMANNUMERALPORT
          value: "3000"
        ports:
        - containerPort: 8099
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-svc
# spec:
#   type: NodePort
#   selector:
#     app: frontend
#   ports:
#     - protocol: TCP
#       nodePort: 31000
#       port: 8099
#       targetPort: 8099 