apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/raymondwcs/to_roman_numeral:frontend
        env:
        - name: ROMANNUMERALPORT
          value: "3000"
        ports:
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 8099
      targetPort: 8099 