apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |
    appendonly yes
    protected-mode no
    bind 0.0.0.0
    port 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      # https://alesnosek.com/blog/2017/02/14/accessing-kubernetes-pods-from-outside-of-the-cluster/
      # hostNetwork: true
      volumes:
        # `name` here must match the name
        # specified in the volume mount
        - name: redis-conf
          # Populate the volume with config map data
          configMap:
            # `name` here must match the name 
            # specified in the ConfigMap's YAML 
            name: redis-conf
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          hostPort: 8888  # allows redis to be connected: redis-cli -h $(minikube ip) -p 8888  
          # The hostPort setting applies to the Kubernetes containers. The container port will be exposed to the external network at <hostIP>:<hostPort>, where the hostIP is the IP address of the Kubernetes node where the container is running and the hostPort is the port requested by the user. 
        command:
          - redis-server
        args:
          - /etc/redis/redis.conf
        volumeMounts:
        # `name` here must match the name
        # from the volumes section of this pod
          - name: redis-conf
            mountPath: /etc/redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  #type: NodePort
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - protocol: TCP
      nodePort: 32555
      port: 6379
      targetPort: 6379
