apiVersion: apps/v1
kind: Deployment
metadata:
  name: roman-numeral-monolithic
  labels:
    app: roman-numeral-monolithic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roman-numeral-frontend
  template:
    metadata:
      labels:
        app: roman-numeral-frontend
    spec:
      containers:
      - name: roman-numeral-monolithic
        image: docker.io/raymondwcs/to_roman_numeral
        imagePullPolicy: Always
        ports:
        - containerPort: 8099

