apiVersion: v1
kind: Service
metadata:
  name: roman-numeral
spec:
  type: NodePort
  selector:
    app: roman-numeral-frontend
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 8099
      targetPort: 8099 
