apiVersion: v1
kind: Service
metadata:
  name: to-roman-numeral-svc
spec:
  type: NodePort
  selector:
    app: to-roman-numeral
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 8099
      targetPort: 8099 
